# image will be published to ghcr.io/<user>/<name>
name: acadia
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 40 # latest is also supported if you want new updates ASAP

#stages
# stages:
#   - name: 
# module configuration, executed in order
# you can include multiple instances of the same module
modules:

  - type: akmods
    base: main
    install:
      - openrgb
      - ryzen-smu
      - xpadneo

  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
                       # put configuration files you want in /usr/etc/ inside the image
                       # while putting files in /etc/ is done on booted system by system administrators.
                       # read more about this in files module reference.

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://packages.microsoft.com/yumrepos/vscode/config.repo
    keys:
     - https://packages.microsoft.com/keys/microsoft.asc
    install:
      - code-insiders
      - keepassxc
      - virt-manager
      - libvirt
      - virt-install
      - edk2-ovmf
      - qemu-kvm

      # - micro
      # - starship
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - com.google.Chrome
        # - org.mozilla.firefox
        # - org.gnome.Loupe
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog
    user:
      repo-title: "Flathub (user)"
      install:
        # Internet
        - com.discordapp.Discord

        # Productivity
        - org.onlyoffice.desktopeditors

        # Creative
        - org.kde.kdenlive
        - org.kde.krita
        - org.blender.Blender

        # Gaming
        - net.lutris.Lutris
        - com.valvesoftware.Steam
        - org.prismlauncher.PrismLauncher

        # Devel
        - io.github.shiftey.Desktop
  
  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - JetBrainsMono
        - SourceCodePro
      google-fonts:
        - Roboto

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

